-- YouTube Transcript Automation - Initial Database Schema
-- Date: 2025-11-02
-- Description: Creates tables for tracking YouTube videos and their transcripts

-- Videos table: Tracks processing status of YouTube videos
CREATE TABLE IF NOT EXISTS public.videos (
  id TEXT PRIMARY KEY,                     -- YouTube video_id
  title TEXT NOT NULL,                      -- Video title from YouTube
  published_at TIMESTAMPTZ NOT NULL,        -- YouTube publish date
  duration_sec INT,                         -- Video length in seconds
  status TEXT NOT NULL DEFAULT 'queued',    -- Processing status: queued | processing | succeeded | failed
  processed_at TIMESTAMPTZ,                 -- When we finished processing
  notes TEXT,                               -- Error messages or additional info
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Transcripts table: Stores the actual transcript data
CREATE TABLE IF NOT EXISTS public.transcripts (
  video_id TEXT PRIMARY KEY                 -- References videos.id
    REFERENCES public.videos(id) ON DELETE CASCADE,
  source TEXT NOT NULL DEFAULT 'deepgram',  -- STT provider (currently only 'deepgram')
  language TEXT,                            -- Detected or specified language code (e.g., 'en')
  text TEXT NOT NULL,                       -- Full transcript as plain text
  segments JSONB,                           -- Word-level timings (NULL for Phase 1)
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Optional: Settings table for channel configuration
-- Useful if you want to store channel_id in DB instead of ENV
CREATE TABLE IF NOT EXISTS public.settings (
  key TEXT PRIMARY KEY,
  value JSONB,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for query performance

-- Index on videos.published_at for chronological queries
CREATE INDEX IF NOT EXISTS idx_videos_published_at
  ON public.videos(published_at DESC);

-- Index on videos.status for filtering by processing state
CREATE INDEX IF NOT EXISTS idx_videos_status
  ON public.videos(status);

-- Index on videos.created_at for recent video queries
CREATE INDEX IF NOT EXISTS idx_videos_created_at
  ON public.videos(created_at DESC);

-- Comments for documentation
COMMENT ON TABLE public.videos IS 'Tracks YouTube videos and their processing status';
COMMENT ON TABLE public.transcripts IS 'Stores transcripts generated by Deepgram STT';
COMMENT ON TABLE public.settings IS 'Application configuration settings (optional)';

COMMENT ON COLUMN public.videos.id IS 'YouTube video ID (e.g., dQw4w9WgXcQ)';
COMMENT ON COLUMN public.videos.status IS 'Processing status: queued, processing, succeeded, or failed';
COMMENT ON COLUMN public.videos.notes IS 'Error messages or retry information';

COMMENT ON COLUMN public.transcripts.text IS 'Full transcript text without timestamps';
COMMENT ON COLUMN public.transcripts.segments IS 'JSONB array of word-level timings (unused in Phase 1)';

-- Sample insert for settings (optional)
-- INSERT INTO public.settings (key, value) VALUES
--   ('channel_id', '"UCxxxxxxxxxxxxxxxx"'::jsonb)
-- ON CONFLICT (key) DO NOTHING;
