-- Fresh Install Script
-- This script will clean up existing tables and create fresh ones
-- Run this in Supabase SQL Editor for a clean installation

-- ==============================================================================
-- STEP 1: CLEANUP - Drop existing tables
-- ==============================================================================

DROP TABLE IF EXISTS public.transcripts CASCADE;
DROP TABLE IF EXISTS public.videos CASCADE;
DROP TABLE IF EXISTS public.settings CASCADE;

-- Drop any indexes that might exist
DROP INDEX IF EXISTS idx_videos_published_at;
DROP INDEX IF EXISTS idx_videos_status;
DROP INDEX IF EXISTS idx_videos_created_at;

-- ==============================================================================
-- STEP 2: CREATE FRESH TABLES
-- ==============================================================================

-- Videos table: Tracks processing status of YouTube videos
CREATE TABLE public.videos (
  id TEXT PRIMARY KEY,                     -- YouTube video_id
  title TEXT NOT NULL,                      -- Video title from YouTube
  published_at TIMESTAMPTZ NOT NULL,        -- YouTube publish date
  duration_sec INT,                         -- Video length in seconds
  status TEXT NOT NULL DEFAULT 'queued',    -- Processing status: queued | processing | succeeded | failed
  processed_at TIMESTAMPTZ,                 -- When we finished processing
  notes TEXT,                               -- Error messages or additional info
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Transcripts table: Stores the actual transcript data
CREATE TABLE public.transcripts (
  video_id TEXT PRIMARY KEY                 -- References videos.id
    REFERENCES public.videos(id) ON DELETE CASCADE,
  source TEXT NOT NULL DEFAULT 'deepgram',  -- STT provider (currently only 'deepgram')
  language TEXT,                            -- Detected or specified language code (e.g., 'en')
  text TEXT NOT NULL,                       -- Full transcript as plain text
  segments JSONB,                           -- Word-level timings (NULL for Phase 1)
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Optional: Settings table for channel configuration
CREATE TABLE public.settings (
  key TEXT PRIMARY KEY,
  value JSONB,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ==============================================================================
-- STEP 3: CREATE INDEXES
-- ==============================================================================

-- Index on videos.published_at for chronological queries
CREATE INDEX idx_videos_published_at
  ON public.videos(published_at DESC);

-- Index on videos.status for filtering by processing state
CREATE INDEX idx_videos_status
  ON public.videos(status);

-- Index on videos.created_at for recent video queries
CREATE INDEX idx_videos_created_at
  ON public.videos(created_at DESC);

-- ==============================================================================
-- STEP 4: ADD COMMENTS
-- ==============================================================================

COMMENT ON TABLE public.videos IS 'Tracks YouTube videos and their processing status';
COMMENT ON TABLE public.transcripts IS 'Stores transcripts generated by Deepgram STT';
COMMENT ON TABLE public.settings IS 'Application configuration settings (optional)';

COMMENT ON COLUMN public.videos.id IS 'YouTube video ID (e.g., dQw4w9WgXcQ)';
COMMENT ON COLUMN public.videos.status IS 'Processing status: queued, processing, succeeded, or failed';
COMMENT ON COLUMN public.videos.notes IS 'Error messages or retry information';

COMMENT ON COLUMN public.transcripts.text IS 'Full transcript text without timestamps';
COMMENT ON COLUMN public.transcripts.segments IS 'JSONB array of word-level timings (unused in Phase 1)';

-- ==============================================================================
-- DONE!
-- ==============================================================================

DO $$
BEGIN
    RAISE NOTICE '✅ Fresh installation complete!';
    RAISE NOTICE '   - videos table created';
    RAISE NOTICE '   - transcripts table created';
    RAISE NOTICE '   - settings table created';
    RAISE NOTICE '   - All indexes created';
    RAISE NOTICE '   ';
    RAISE NOTICE 'Your database is ready to use! 🚀';
END $$;
